filter client orders
zetamarkets/sdk pull request #181
Opened 2022-12-22 05:39 UTC by kelvinlau20100

2022-12-22 06:42 UTC, xjcaa requested changes

2022-12-22 06:42 UTC, xjcaa commented on src/subclient.ts
> +        order.side == types.Side.BID ? true : false
Can't this just be side == bid without the ternary

2022-12-22 07:15 UTC, kelvinlau20100 commented on src/subclient.ts
> +        order.side == types.Side.BID ? true : false
Whoops yes

2022-12-23 05:49 UTC, xjcaa approved these changes

2022-12-23 05:49 UTC, merged